generate:
	cd atom && make generate
	cd storage_location && make generate
	cd elementary_type_name && make generate
	cd state_mutability && make generate
	cd visibility && make generate
	cd literal && make generate
	cd definition && make generate
