program = _{ SOI ~ pragma_directive ~ EOI }
pragma_directive = { pragma ~ identifier ~ consume_until_semi ~ semi }

pragma_statement = { pragma ~ identifier ~ consume_until_semi ~ semi }


pragma = _{ "pragma" }
semi = _ { ";" }
not_semi = { !semi ~ ANY }
consume_until_semi = @{ not_semi+ }

identifier = @{ (ASCII_ALPHA | "_" | "$") ~ (ASCII_ALPHANUMERIC | "_" | "$")* }

WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
